image: golang:1.14.2

variables:
    IMAGE_NAME: rg-db-prod
    BUILD_PATH: /builds/masterback/rg-db
    TARGET_SERVER: gitupdater@dockertest.rgwork.ru

stages:
    - deploy&copy
    - deploy&compose
    - message_on_success
    - message_on_failure


deploy&copy:
    stage: deploy&copy
    script:
        # - ./sh/build-executable.sh  
        - ./sh/build-deploy-directory.sh  
        - ./.import-ssh-key.sh "$PROD_RSA_PRIVATE_KEY"
        # remove old dir on the server
        - ssh $TARGET_SERVER 'rm -rf /home/gitupdater/'$IMAGE_NAME
        # copy new dir on server
        - scp -pr $BUILD_PATH/deploy $TARGET_SERVER:/home/gitupdater/$IMAGE_NAME
        # чтоб можно было сохранять файлы 
        - ssh $TARGET_SERVER "chmod -R 7777 /home/gitupdater/$IMAGE_NAME/notebooks"
        # - rsync -av $BUILD_PATH/deploy $TARGET_SERVER:/home/gitupdater/$IMAGE_NAME
        # change rights to filebeat (permition denied)
        # - ssh $TARGET_SERVER 'chown root /home/gitupdater/'$IMAGE_NAME/configs/filebeat.yml

    only:
        - production


deploy&compose:
    stage: deploy&compose
    dependencies:
        - deploy&copy
    script:
        - ./.import-ssh-key.sh "$DEPLOY_RSA_PRIVATE_KEY"
        # !!! start real deploy and docker-compose
        - ssh $TARGET_SERVER $IMAGE_NAME
    only:
        - production


message_on_success:
    stage: message_on_success
    allow_failure: true
    dependencies:
        - deploy&compose
    when: on_success
    script:
        # send to telegram proxy
        - curl -v http://proxy.govoru.com/?message=%E2%9C%85%20Success.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20completed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    only:
        - production


message_on_failure:
    stage: message_on_failure
    allow_failure: true
    dependencies:
        - deploy&compose
    when: on_failure
    script:
        # send to telegram proxy
        - curl -v http://proxy.govoru.com/?message=%E2%9D%8C%20Error.%20Auto%20deploy%20on%20${CI_PROJECT_NAME}%20is%20failed,%20Pipeline:%20${CI_PIPELINE_URL}%20by%20${GITLAB_USER_LOGIN}
    only:
        - production
