version: '3.1'

services:
  # база данных
  rg-db-prod:
    image: postgres:10.9-alpine
    container_name: rg-db-prod
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - rg-db-data:/var/lib/postgresql/data/pgdata
      - rg-db-data-dumps:/dumps
      #  - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${RGPASS}
      POSTGRES_DB: rgdb 
      PGDATA: /var/lib/postgresql/data/pgdata
    # command: sleep 10000

  # импорт csv в Эластик
  rg-db-notebook:
    build: 
        context: .
        dockerfile: Dockerfile-base-notebook 
    container_name: rg-db-notebook
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes: 
        - .:/home/jovyan/work
  
# Данные
volumes:
  rg-db-data:
    external: true
  rg-db-data-dumps:
    external: true
      
# outer network to communicate with other services ----------------------------------------------------
networks:
  default:
    external:
        name: auth_proxy_network

