version: '3.1'

services:

  db:
    image: postgres:10.9-alpine
    container_name: rgdb-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "/home/gitupdater/rgdb/pgdata:/var/lib/postgresql/data/pgdata"
      - "./dumps:/dumps"
      #  - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rgdb 
      PGDATA: /var/lib/postgresql/data/pgdata

# outer network to communicate with other services ----------------------------------------------------
  networks:
    default:
        external:
            name: auth_proxy_network

